### ISSUE TITLE
Are you forgot about round after each operation?

### ISSUE THREAD

**Issue by munrocket** [sukop/doubledouble#1]
Look at this article please, he use round function after each iteration.
https://www.codeproject.com/Articles/884606/The-double-double-type

**Comment by sukop** [comment]
Sorry, not sure I follow, do you mean `RN()`? If so, then it simply means "In all of the following, the notation RN( ) implies that the operation should be performed with rounding to nearest or even" (from the link).

**Comment by munrocket** [comment]
Yes, i am about it. I am trying to port double-double in javascript.
So you just use all sugnificant number and this is ok?

**Comment by sukop** [comment]
Not sure what you mean by "all s[i]gnificant number" but the idea is that this`RN()` is performed by default, no need to manually "round" the results.

**Comment by munrocket** [comment]
Thank you for your quick reply! (I mean significant digits in float)
